name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  WGPU_BACKEND: vulkan
  # WGPU_POWER_PREF: low

jobs:
  build-debug:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v6

      - name: Install Vulkan + SwiftShader
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libvulkan1 \
            vulkan-tools \
            mesa-vulkan-drivers

      - name: Verify Vulkan
        run: vulkaninfo | head -n 50

      - name: Build
        run: cargo build

      - name: Run tests (wgpu compute)
        run: cargo test --verbose


  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Install Vulkan + SwiftShader
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libvulkan1 \
            vulkan-tools \
            mesa-vulkan-drivers

      - name: Verify Vulkan
        run: vulkaninfo | head -n 50

      - name: Build
        run: cargo build

      - name: Run tests (wgpu compute, --release)
        env:
          TEST_ENABLE_SLOW_TESTS: true
          TEST_MAX_DATA_SIZE_MIB: 256
        run: cargo test --verbose --release

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - build-release
      - build-debug
    if: github.event_name == 'release'
    permissions:
      id-token: write     # Required for OIDC token exchange.
    steps:
      - uses: actions/checkout@v6
      
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
